version: '3.8'

services:
  go_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    env_file:
      - .env
    ports:
      - "8081:8080"  # Измените порт на хосте
    networks:
      - auth-network

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge