definitions:
  docs.AccessRequest:
    properties:
      role:
        type: integer
      url:
        type: string
    type: object
  docs.AccessToken:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      token_type:
        type: string
    type: object
  docs.ErrorResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  docs.ForgotPasswordRequest:
    properties:
      email:
        type: string
    type: object
  docs.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  docs.RefreshRequest:
    properties:
      refresh_token:
        type: string
    type: object
  docs.ResetPasswordRequest:
    properties:
      new_password:
        type: string
      token:
        type: string
    type: object
  docs.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
  docs.SuccessResponseWithoutData:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  docs.Token:
    properties:
      access_expires_in:
        type: integer
      access_token:
        type: string
      refresh_expires_in:
        type: integer
      refresh_token:
        type: string
      token_type:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/access:
    post:
      consumes:
      - application/json
      description: Проверяет доступ к заданному маршруту на основе роли
      parameters:
      - description: Роль и маршрут
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/docs.AccessRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Доступ разрешён
          schema:
            $ref: '#/definitions/docs.SuccessResponseWithoutData'
        "400":
          description: Недействительные данные
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
        "401":
          description: Недействительный или отсутствующий токен
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
      summary: Проверка прав доступа
      tags:
      - Auth
  /auth/check:
    get:
      description: Проверяет валидность переданного access-токена
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Токен действителен
          schema:
            $ref: '#/definitions/docs.SuccessResponseWithoutData'
        "401":
          description: Токен недействителен или отсутствует
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
      summary: Проверка токена
      tags:
      - Auth
  /auth/forgot-password:
    post:
      consumes:
      - application/json
      description: Отправляет ссылку для восстановления доступа
      parameters:
      - description: Email для восстановления
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/docs.ForgotPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Ссылка для восстановления отправлена
          schema:
            $ref: '#/definitions/docs.SuccessResponseWithoutData'
        "400":
          description: Некорректный запрос
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
      summary: Восстановление пароля
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Аутентифицирует пользователя и выдаёт JWT-токены
      parameters:
      - description: Данные для входа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/docs.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешная авторизация
          schema:
            allOf:
            - $ref: '#/definitions/docs.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/docs.Token'
              type: object
        "400":
          description: Неверные учётные данные
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
        "403":
          description: Пользователь заблокирован
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
      summary: Вход пользователя
      tags:
      - Auth
  /auth/logout:
    post:
      description: Завершает сессию пользователя
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Сессия завершена
          schema:
            $ref: '#/definitions/docs.SuccessResponseWithoutData'
        "401":
          description: Неавторизованный доступ
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
      summary: Выход пользователя
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Обновляет access-токен с помощью refresh-токена
      parameters:
      - description: Refresh-токен
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/docs.RefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Новый токен получен
          schema:
            allOf:
            - $ref: '#/definitions/docs.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/docs.AccessToken'
              type: object
        "400":
          description: Некорректный запрос
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
        "401":
          description: Недействительный или истекший refresh-токен
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
      summary: Обновление токена
      tags:
      - Auth
  /auth/reset-password:
    post:
      consumes:
      - application/json
      description: Сбрасывает пароль по ссылке для восстановления
      parameters:
      - description: Новый пароль
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/docs.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Пароль изменён
          schema:
            $ref: '#/definitions/docs.SuccessResponseWithoutData'
        "400":
          description: Токен недействителен или истек
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
      summary: Сброс пароля
      tags:
      - Auth
swagger: "2.0"
